resolve issue #365 in original repo
hassio-addons/addon-nginx-proxy-manager pull request #368
Opened 2022-10-07 18:05 UTC by nlhomme

# Proposed Changes

> (Describe the changes and rationale behind them)

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

2022-10-07 18:18 UTC, rcmurphy commented
This is amazing. Thank you!

2022-10-08 09:49 UTC, frenck requested changes
This is not blocking startup. Thus not correct.

2022-10-08 13:00 UTC, rcmurphy commented
Typically when rejecting a PR, it’s best to keep the feedback constructive, instead of just saying “wrong”. @frenck could you articulate your issues with the PR?On Oct 8, 2022, at 05:50, Franck Nijhof ***@***.***> wrote:﻿
@frenck requested changes on this pull request.

This is not blocking startup. Thus not correct.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2022-10-08 16:08 UTC, nlhomme commented
Hi,

I'm sorry for the empty description (now completed), it's not a lack of motivation, it is an oversight.

Regards

Nicolas

2022-10-08 16:30 UTC, nlhomme commented
I'm also sorry for the noise made by the "repository.yaml" file, it was a test file created in the wrong branch...

2022-10-08 17:09 UTC, sinclairpaul commented
Is the intention to switch the addon from using MariaDB to using SQLite?  As the addon has been implemented based on having MariaDB as the backend.

If it is the case, how would you migrate the users data?, as an example if I am currently running the addon and for some reason I stop MariaDB, and restart NPM in this scenario it would start up with a blank SQLite DB.  This won't include any of my configuration which is used to generate the Nginx config and manage the certificates.  The proxy may still function as they are generated config files, however the application won't be fully functional.

I know there have been some issues relating to MariaDB and startup due to Watchdog, which I believe caused issues in it then returning the correct data for this addon to start.  In order to fix that there needs to be a check somewhere to ensure the necessary config isn't null.

2022-10-08 18:17 UTC, rcmurphy commented
My intent was that one could pick MariaDB or SQLite for their install. Migration would not be supported.

2022-11-16 08:22 UTC, closed without merging